language: php

notifications:
  email:
    on_success: never
    on_failure: change

php:
  - 8.0

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 8.0
      env: WP_VERSION=latest WP_MULTISITE=1

script: phpunit
